### ISSUE TITLE
[Proposal]: Reproducible Machine Learning Workflows for Scientists

### ISSUE THREAD

**Issue by matthewfeickert** [carpentries-incubator/proposals#222]
### 1. Lesson Topic

Scientific researchers need reproducible software environments for complex applications that can run across heterogeneous computing platforms. Modern open source tools, like [Pixi](https://pixi.sh/), provide automatic reproducibility solutions for all dependencies while providing a high level interface well suited for researchers.

This lesson will provide an introduction to using Pixi to easily create scientific and AI/ML environments that benefit from hardware acceleration, across multiple machines and platforms. The focus will be on applications using the PyTorch and JAX Python machine learning libraries with CUDA enabled, as well as deploying these environments to production settings in Linux container images.

### 2. Lesson Language

English

### 3. Draft materials

No, not really. I have disparate pieces of past research and exploration, but I am currently putting together a course as part of work associated with a fellowship award.

### 4. Requirements for existing materials

- [N/A] do your lesson materials conform to our [Code of Conduct](https://docs.carpentries.org/topic_folders/policies/code-of-conduct.html#code-of-conduct-summary-view)?
- [N/A] are your materials already on GitHub and do they use The Carpentries [lesson template](https://github.com/carpentries/styles) or [The Carpentries Workbench](https://carpentries.github.io/workbench/)? (you can visit [the Workbench tutorial](https://carpentries.github.io/sandpaper-docs/) to learn more about how to use our lesson infrastructure).

### 5. New repository creation

- [x] I need a new repository created

### 6. Transfer existing repository

- [N/A] my lesson meets both criteria in part 4 and I would like to transfer the repository to The Carpentries Incubator

### 7. Collaborators

@qualiaMachine @rbemowski

### 8. Info/Questions

This lesson is being developed as part of a workshop series for the US Research Software Sustainability Institute in 2025.

**Comment by tobyhodges** [comment]
Thanks for this lesson proposal @matthewfeickert.

I have created the repository for you at https://github.com/carpentries-incubator/reproducible-ml-workflows.

You should have received an invitation to join the maintainer team for this lesson. Please reply here to let me know when you have joined the team, and I will then be able to grant you Admin access to the repository and give you the ability to add and remove collaborators on the maintainer team.

The README of the repository includes a brief list of recommended next steps. You might find [the Workbench documentation](https://carpentries.github.io/sandpaper-docs/) a helpful resource while working with The Carpentries lesson infrastructure. [The Carpentries Curriculum Development Handbook](https://cdh.carpentries.org/) and our [Collaborative Lesson Development Training curriculum](https://carpentries.github.io/lesson-development-training/) provide an overview of the approach we recommend to lesson design and development. But please feel free to post back here or ping me if you get stuck or if you have any further questions. I am always happy to support lesson development!

To keep in touch with The Carpentries curriculum community you may also find it useful to join [the incubator-developers list on The Carpentries TopicBox](https://carpentries.topicbox.com/groups/incubator-developers) and/or [the lesson-dev channel on The Carpentries Slack](https://carpentries.slack.com/archives/C3KUTT5V3).

**Comment by matthewfeickert** [comment]
> I have created the repository for you at https://github.com/carpentries-incubator/reproducible-ml-workflows.

Thanks very much, @tobyhodges!
 
> You should have received an invitation to join the maintainer team for this lesson. Please reply here to let me know when you have joined the team, and I will then be able to grant you Admin access to the repository and give you the ability to add and remove collaborators on the maintainer team.

Done!

**Comment by tobyhodges** [comment]
@matthewfeickert you can [join the Slack via this invite link](https://slack-invite.carpentries.org/)

**Comment by matthewfeickert** [comment]
Thanks very much, @tobyhodges! I think I'm good to go now.

**Comment by tobyhodges** [comment]
Great @matthewfeickert, thanks. I will close this issue now that the repository is set up and you have the appropriate access. I will still receive notifications so please post back here if you have any questions!

**Comment by matthewfeickert** [comment]
Thanks very much @tobyhodges!
